def print_welcome():
    print("                *               ")
    print("  *             *            *  ")
    print("  *             *            *  ")
    print("  *             *            *  ")
    print(" ***           ***          *** ")
    print("*****         *****        *****")
    print("********************************")
    print("********************************")
    print("********************************")
    print("********************************")
    print("________________________________")
    print("*                              *")
    print("*                              *")
    print("* Welcome to our coffee shop recommendation software! *")
    print("*                              *")
    print("*______________________________*")